# Form implementation generated from reading ui file 'competition.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(782, 722)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout_2.addWidget(self.lineEdit)
        self.tableWidget = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.verticalLayout_2.addWidget(self.tableWidget)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_2.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 782, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(parent=self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuShow = QtWidgets.QMenu(parent=self.menubar)
        self.menuShow.setObjectName("menuShow")
        self.menuPrint = QtWidgets.QMenu(parent=self.menubar)
        self.menuPrint.setObjectName("menuPrint")
        self.menuTable = QtWidgets.QMenu(parent=self.menubar)
        self.menuTable.setObjectName("menuTable")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionSave = QtGui.QAction(parent=MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionScorebord = QtGui.QAction(parent=MainWindow)
        self.actionScorebord.setObjectName("actionScorebord")
        self.actionQuit = QtGui.QAction(parent=MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionLoad = QtGui.QAction(parent=MainWindow)
        self.actionLoad.setObjectName("actionLoad")
        self.actionEmpty_metrics = QtGui.QAction(parent=MainWindow)
        self.actionEmpty_metrics.setObjectName("actionEmpty_metrics")
        self.actionFull_scoreboard = QtGui.QAction(parent=MainWindow)
        self.actionFull_scoreboard.setObjectName("actionFull_scoreboard")
        self.actionAdd_row = QtGui.QAction(parent=MainWindow)
        self.actionAdd_row.setCheckable(False)
        self.actionAdd_row.setEnabled(True)
        self.actionAdd_row.setObjectName("actionAdd_row")
        self.actionRemove_row = QtGui.QAction(parent=MainWindow)
        self.actionRemove_row.setObjectName("actionRemove_row")
        self.actionClear = QtGui.QAction(parent=MainWindow)
        self.actionClear.setObjectName("actionClear")
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionLoad)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuShow.addAction(self.actionScorebord)
        self.menuPrint.addAction(self.actionEmpty_metrics)
        self.menuPrint.addAction(self.actionFull_scoreboard)
        self.menuTable.addAction(self.actionClear)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuPrint.menuAction())
        self.menubar.addAction(self.menuTable.menuAction())
        self.menubar.addAction(self.menuShow.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Competition"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuShow.setTitle(_translate("MainWindow", "Show"))
        self.menuPrint.setTitle(_translate("MainWindow", "Print"))
        self.menuTable.setTitle(_translate("MainWindow", "Table"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionScorebord.setText(_translate("MainWindow", "Scoreboard"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
        self.actionLoad.setText(_translate("MainWindow", "Load"))
        self.actionEmpty_metrics.setText(_translate("MainWindow", "Empty metrics"))
        self.actionFull_scoreboard.setText(_translate("MainWindow", "Scoreboard"))
        self.actionAdd_row.setText(_translate("MainWindow", "Add row"))
        self.actionRemove_row.setText(_translate("MainWindow", "Remove row"))
        self.actionClear.setText(_translate("MainWindow", "Clear"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
